# Generated by Django 4.1.7 on 2023-04-15 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('sql_statement', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='QueryResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file', models.CharField(max_length=1024)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.querymodel')),
            ],
        ),
    ]
